#!/bin/sh

if [ $# -le 1 ]
then
  echo "Usage: `basename $0` phpfreechat_path checkmd5_output_filename"
  echo "exempel: `basename $0` ~/pfc/misc/phpfreechat ~/pfc/misc/phpfreechat/checkmd5.php"
  exit;
fi

PFC_PATH=$1
DST=$2
TMP=/tmp/checkmd5.php

if ( test -f $DST )
then
  echo "$DST should not exist. Please delete this file."
  exit;
fi

if ( test ! -f $PFC_PATH/version  )
then
  echo "$PFC_PATH/version doesn't exist."
  exit;
fi
    
echo "--> Creating $DST"

cd $PFC_PATH
echo "<?php" > $TMP
echo 'echo "<h2>Checking phpfreechat files validity</h2>";' >> $TMP
echo 'echo "<pre>\n";' >> $TMP
for f in `find . -type f`
do
  sum=`md5sum $f | sed "s/\s.*$//g"`
  echo 'if (md5(file_get_contents("'$f'")) == "'$sum'")' >> $TMP
  echo '  echo "<span style=\"color:#3A3\">ok - '$f'</span>\n";' >> $TMP
  echo 'else' >> $TMP
  echo '  echo "<span style=\"color:#F33\">corrupted - '$f' (please replace this file by a correct one)</span>\n";' >> $TMP
done
echo 'echo "</pre>\n";' >> $TMP
echo "?>" >> $TMP
cd - >/dev/null

cp $TMP $DST

echo "---> Done, $DST created"
