#!/bin/sh

NAME_TGZ=phpfreechat-`cat ../version.txt`.tar.gz
NAME_ZIP=phpfreechat-`cat ../version.txt`.zip
NAME_SETUP=phpfreechat-`cat ../version.txt`-setup.php

#scp ./$NAME_ZIP ./$NAME_TGZ micropolia@phpfreechat.net:/home/micropolia/svn/phpfreechat/prod/www/download/
lftp -c "mput -O ftp://upload.sourceforge.net/incoming/ $NAME_TGZ"
lftp -c "mput -O ftp://upload.sourceforge.net/incoming/ $NAME_ZIP"
lftp -c "mput -O ftp://upload.sourceforge.net/incoming/ $NAME_SETUP"
