#!/bin/bash
# Script used to test phpfreechat interface with a command line (it uses phantomjs)
# TODO : move this code to a Makefile

# wget http://phantomjs.googlecode.com/files/phantomjs-1.5.0-linux-x86-dynamic.tar.gz
# tar xzf phantomjs-1.5.0-linux-x86-dynamic.tar.gz
./phantomjs/bin/phantomjs ./phantomjs/examples/run-qunit.js http://127.0.0.1:32773/phpfreechat/client/tests/test1.html
