#!/bin/sh

echo "-- creating archive --"
echo "-> copying files"
rm -rf dcchat
svn export .. ./dcchat
svn export ../../.. ./dcchat/phpfreechat
echo "-> creating .tar.gz"
tar czfp dcchat-`cat ../../../version`.tar.gz dcchat/ 
echo "-> creating .zip"
zip -Tq9r dcchat-`cat ../../../version`.zip dcchat/
echo "-> removing temporary files"
rm -rf dcchat
echo "-- creating archive, done --"
